### ISSUE TITLE
(ui) Scheduler: cooking pot visuals

### ISSUE THREAD

**Issue by 0xSaksham** [joinmarket-webui/jam#767]
Will solve this as part of Summer of Bitcoin #319 

- [ ] (ui) Cooking Pot Visual (still with linear progress bar)
- [ ] (ui) Circlular progress bar around Cooking Pot Visual
- [ ] (ui) Better information of active schedule (e.g. transaction ids) (via toggle "Display details")
- [ ] (ui) Confirmation modal before starting (e.g. display fee settings)
- [ ] (backend) Ability to retrieve generated Schedule without starting one
- [ ] (backend) Ability to start a provided Schedule via API
- [ ] (ui) Show generated Schedule before starting (and ability to "randomize" [regenerate])
- [ ] (ui) Include schedule information in confirmation modal

**Comment by theborakompanioni** [comment]
@0xSaksham Thanks for creating the ticket. Looking forward to the Cooking Pot! Finally :smiling_face_with_tear:

**Comment by 0xSaksham** [comment]
#783 Finishes this. Please take a look @theborakompanioni. Thanks!

**Comment by 0xSaksham** [comment]
Right so, this issue is already implemented. I'll start making it round and adding the Cooking Pot Animation.
